//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnNhanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.CT_HD = new HashSet<CT_HD>();
        }
    
        public int MaHd { get; set; }
        public System.DateTime Ngay { get; set; }
        public string Tk { get; set; }
        public Nullable<int> MaKm { get; set; }
        public Nullable<int> MaCb { get; set; }
        public Nullable<int> ThanhTien { get; set; }
    
        public virtual Combo Combo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_HD> CT_HD { get; set; }
        public virtual KhuyenMai KhuyenMai { get; set; }
        public virtual Tk Tk1 { get; set; }
    }
}
