//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnNhanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_login
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Login { get; set; }
        public Nullable<System.DateTime> Logout { get; set; }
        public string TK { get; set; }
    
        public virtual Tk Tk1 { get; set; }
    }
}
